import = ["~/.config/alacritty/ayu_dark.toml"]

[env]
TERM = "screen-256color"

[shell]
program = "/bin/zsh"
args = ["-l"]

# Hack Nerd Font: https://github.com/ryanoasis/nerd-fonts/releases
# Maple Font: https://github.com/subframe7536/maple-font
[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }

size = 15
# offset.x = 0
offset.y = 4
glyph_offset.y = 2

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[window]
decorations = 'Buttonless'
opacity = 0.5
blur = true
dynamic_padding = true
decorations_theme_variant = 'Dark'
padding = { x = 3, y = 3 }

[scrolling]
history = 5000

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"
