import = [
 "~/.config/alacritty/ayu_dark.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-l"]

# Hack Nerd Font: https://github.com/ryanoasis/nerd-fonts/releases
# Maple Font: https://github.com/subframe7536/maple-font
[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular"}
bold = { family = "FiraCode Nerd Font Mono", style = "Bold"}
italic = { family = "FiraCode Nerd Font Mono", style = "Light Italic"}
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic"}

size = 15
# offset.x = 0
offset.y = 4
glyph_offset.y = 2

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[window]
decorations = 'Buttonless'
opacity = 0.95
blur = true
dynamic_padding = true
decorations_theme_variant = 'Dark'
padding = { x = 3, y = 3 }

[scrolling]
history = 5000

