import = [
 "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MonoLisa Nerd Font", style = "Regular"}
bold = { family = "MonoLisa Nerd Font", style = "Bold"}
italic = { family = "MonoLisa Nerd Font", style = "Light Italic"}
bold_italic = { family = "MonoLisa Nerd Font", style = "Bold Italic"}

size = 15
offset.x = 0
offset.y = 5

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[window]
decorations = 'Buttonless'
opacity = 0.95
blur = true
dynamic_padding = true
decorations_theme_variant = 'Dark'
padding = { x = 3, y = 3 }

[scrolling]
history = 5000

